global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'quest-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['quest-service:3000']

  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-service:3000']

  - job_name: 'social-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['social-service:3000']